### ISSUE TITLE
A bug appear during runtime

### ISSUE THREAD

**Issue by samwu-learn** [sribdcn/anoymous_MIP_method#1]
Hello, thank you for your excellent work. I hope to replicate your work, so I ran the code and found the following error when running Python trainPredictModel. py. 

/anaconda3/envs/gurobi/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize
    return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))
RuntimeError: CUDA error: out of memory
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by CenturionMKIII** [comment]
> Hello, thank you for your excellent work. I hope to replicate your work, so I ran the code and found the following error when running Python trainPredictModel. py.
> 
> /anaconda3/envs/gurobi/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize return torch.UntypedStorage(obj.nbytes(), device=torch.device(location)) RuntimeError: CUDA error: out of memory Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Hi, thank you very much for your comment. This issue can be solved by reducing the size of batch in L30 of trainPredictModel.py. Please feel free to contact if you have any other concerns.

**Comment by Transtars** [comment]
> > Hello, thank you for your excellent work. I hope to replicate your work, so I ran the code and found the following error when running Python trainPredictModel. py.
> > /anaconda3/envs/gurobi/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize return torch.UntypedStorage(obj.nbytes(), device=torch.device(location)) RuntimeError: CUDA error: out of memory Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> Hi, thank you very much for your comment. This issue can be solved by reducing the size of batch in L30 of trainPredictModel.py. Please feel free to contact if you have any other concerns.

hello，I also encountered 'RuntimeError: CUDA error: out of memory', but it did not appear during the training process, but during the call to gurobi. py. Here are some detailed error reports:
Process Process-97:
Traceback (most recent call last):
File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 315, in_ Bootstrap
Self. run()
File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 108, in run
Self_ Target (* self. args, * * self. _kwargs)
File "/home/cc/code/Predict and Search-MILP_method main/globi. py", line 82, in collect
A2, v_ Map2, v_ Nodes2, c_ Nodes2, b_ Vars2=get_ A_ New2 (filepath)
File "/home/cc/code/Predict and Search-MILP_method main/helper. py", line 467, in get_ A_ New2
V_ Nodes=torch. as_ Tensor (v_nodes, dtype=torch. float32). to (device) # Variable nodes # TODO device
RuntimeError: CUDA error: out of memory

**Comment by CenturionMKIII** [comment]
> > > Hello, thank you for your excellent work. I hope to replicate your work, so I ran the code and found the following error when running Python trainPredictModel. py.
> > > /anaconda3/envs/gurobi/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize return torch.UntypedStorage(obj.nbytes(), device=torch.device(location)) RuntimeError: CUDA error: out of memory Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > 
> > 
> > Hi, thank you very much for your comment. This issue can be solved by reducing the size of batch in L30 of trainPredictModel.py. Please feel free to contact if you have any other concerns.
> 
> hello，I also encountered 'RuntimeError: CUDA error: out of memory', but it did not appear during the training process, but during the call to gurobi. py. Here are some detailed error reports: Process Process-97: Traceback (most recent call last): File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 315, in_ Bootstrap Self. run() File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 108, in run Self_ Target (* self. args, * * self. _kwargs) File "/home/cc/code/Predict and Search-MILP_method main/globi. py", line 82, in collect A2, v_ Map2, v_ Nodes2, c_ Nodes2, b_ Vars2=get_ A_ New2 (filepath) File "/home/cc/code/Predict and Search-MILP_method main/helper. py", line 467, in get_ A_ New2 V_ Nodes=torch. as_ Tensor (v_nodes, dtype=torch. float32). to (device) # Variable nodes # TODO device RuntimeError: CUDA error: out of memory

Hi, thank you for your interest. Since we are extracting features from the original problem, this could happen as the problem sizes become too large. One possible solution is to try on presolved instances where redundant columns are removed.

**Comment by Transtars** [comment]
> > > > Hello, thank you for your excellent work. I hope to replicate your work, so I ran the code and found the following error when running Python trainPredictModel. py.
> > > > /anaconda3/envs/gurobi/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize return torch.UntypedStorage(obj.nbytes(), device=torch.device(location)) RuntimeError: CUDA error: out of memory Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > > 
> > > 
> > > Hi, thank you very much for your comment. This issue can be solved by reducing the size of batch in L30 of trainPredictModel.py. Please feel free to contact if you have any other concerns.
> > 
> > 
> > hello，I also encountered 'RuntimeError: CUDA error: out of memory', but it did not appear during the training process, but during the call to gurobi. py. Here are some detailed error reports: Process Process-97: Traceback (most recent call last): File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 315, in_ Bootstrap Self. run() File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 108, in run Self_ Target (* self. args, * * self. _kwargs) File "/home/cc/code/Predict and Search-MILP_method main/globi. py", line 82, in collect A2, v_ Map2, v_ Nodes2, c_ Nodes2, b_ Vars2=get_ A_ New2 (filepath) File "/home/cc/code/Predict and Search-MILP_method main/helper. py", line 467, in get_ A_ New2 V_ Nodes=torch. as_ Tensor (v_nodes, dtype=torch. float32). to (device) # Variable nodes # TODO device RuntimeError: CUDA error: out of memory
> 
> Hi, thank you for your interest. Since we are extracting features from the original problem, this could happen as the problem sizes become too large. One possible solution is to try on presolved instances where redundant columns are removed.

Thank you. Based on the information you provided, I have resolved the problem I encountered.

**Comment by XuNing525** [comment]
> > > > > Hello, thank you for your excellent work. I hope to replicate your work, so I ran the code and found the following error when running Python trainPredictModel. py.
> > > > > /anaconda3/envs/gurobi/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize return torch.UntypedStorage(obj.nbytes(), device=torch.device(location)) RuntimeError: CUDA error: out of memory Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > > > 
> > > > 
> > > > Hi, thank you very much for your comment. This issue can be solved by reducing the size of batch in L30 of trainPredictModel.py. Please feel free to contact if you have any other concerns.
> > > 
> > > 
> > > hello，I also encountered 'RuntimeError: CUDA error: out of memory', but it did not appear during the training process, but during the call to gurobi. py. Here are some detailed error reports: Process Process-97: Traceback (most recent call last): File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 315, in_ Bootstrap Self. run() File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 108, in run Self_ Target (* self. args, * * self. _kwargs) File "/home/cc/code/Predict and Search-MILP_method main/globi. py", line 82, in collect A2, v_ Map2, v_ Nodes2, c_ Nodes2, b_ Vars2=get_ A_ New2 (filepath) File "/home/cc/code/Predict and Search-MILP_method main/helper. py", line 467, in get_ A_ New2 V_ Nodes=torch. as_ Tensor (v_nodes, dtype=torch. float32). to (device) # Variable nodes # TODO device RuntimeError: CUDA error: out of memory
> > 
> > 
> > Hi, thank you for your interest. Since we are extracting features from the original problem, this could happen as the problem sizes become too large. One possible solution is to try on presolved instances where redundant columns are removed.
> 
> Thank you. Based on the information you provided, I have resolved the problem I encountered.

Hello， have you replicated this work? I don't know how to get primal gap to plot Figure about time and average primal gap, could you give me some help?

**Comment by Transtars** [comment]
> > > > > > Hello, thank you for your excellent work. I hope to replicate your work, so I ran the code and found the following error when running Python trainPredictModel. py.
> > > > > > /anaconda3/envs/gurobi/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize return torch.UntypedStorage(obj.nbytes(), device=torch.device(location)) RuntimeError: CUDA error: out of memory Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > > > > 
> > > > > 
> > > > > Hi, thank you very much for your comment. This issue can be solved by reducing the size of batch in L30 of trainPredictModel.py. Please feel free to contact if you have any other concerns.
> > > > 
> > > > 
> > > > hello，I also encountered 'RuntimeError: CUDA error: out of memory', but it did not appear during the training process, but during the call to gurobi. py. Here are some detailed error reports: Process Process-97: Traceback (most recent call last): File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 315, in_ Bootstrap Self. run() File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 108, in run Self_ Target (* self. args, * * self. _kwargs) File "/home/cc/code/Predict and Search-MILP_method main/globi. py", line 82, in collect A2, v_ Map2, v_ Nodes2, c_ Nodes2, b_ Vars2=get_ A_ New2 (filepath) File "/home/cc/code/Predict and Search-MILP_method main/helper. py", line 467, in get_ A_ New2 V_ Nodes=torch. as_ Tensor (v_nodes, dtype=torch. float32). to (device) # Variable nodes # TODO device RuntimeError: CUDA error: out of memory
> > > 
> > > 
> > > Hi, thank you for your interest. Since we are extracting features from the original problem, this could happen as the problem sizes become too large. One possible solution is to try on presolved instances where redundant columns are removed.
> > 
> > 
> > Thank you. Based on the information you provided, I have resolved the problem I encountered.
> 
> Hello， have you replicated this work? I don't know how to get primal gap to plot Figure about time and average primal gap, could you give me some help?

Hello. For some reasons, I have not replicated this work and have instead moved on to other work.  I regret that I couldn't be of help to you.

**Comment by XuNing525** [comment]
> > > > > > > Hello, thank you for your excellent work. I hope to replicate your work, so I ran the code and found the following error when running Python trainPredictModel. py.
> > > > > > > /anaconda3/envs/gurobi/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize return torch.UntypedStorage(obj.nbytes(), device=torch.device(location)) RuntimeError: CUDA error: out of memory Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > > > > > 
> > > > > > 
> > > > > > Hi, thank you very much for your comment. This issue can be solved by reducing the size of batch in L30 of trainPredictModel.py. Please feel free to contact if you have any other concerns.
> > > > > 
> > > > > 
> > > > > hello，I also encountered 'RuntimeError: CUDA error: out of memory', but it did not appear during the training process, but during the call to gurobi. py. Here are some detailed error reports: Process Process-97: Traceback (most recent call last): File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 315, in_ Bootstrap Self. run() File "/home/cc/anaconde3/envs/pytest/lib/python3.8/multiprocessing/process. py", line 108, in run Self_ Target (* self. args, * * self. _kwargs) File "/home/cc/code/Predict and Search-MILP_method main/globi. py", line 82, in collect A2, v_ Map2, v_ Nodes2, c_ Nodes2, b_ Vars2=get_ A_ New2 (filepath) File "/home/cc/code/Predict and Search-MILP_method main/helper. py", line 467, in get_ A_ New2 V_ Nodes=torch. as_ Tensor (v_nodes, dtype=torch. float32). to (device) # Variable nodes # TODO device RuntimeError: CUDA error: out of memory
> > > > 
> > > > 
> > > > Hi, thank you for your interest. Since we are extracting features from the original problem, this could happen as the problem sizes become too large. One possible solution is to try on presolved instances where redundant columns are removed.
> > > 
> > > 
> > > Thank you. Based on the information you provided, I have resolved the problem I encountered.
> > 
> > 
> > Hello， have you replicated this work? I don't know how to get primal gap to plot Figure about time and average primal gap, could you give me some help?
> 
> Hello. For some reasons, I have not replicated this work and have instead moved on to other work. I regret that I couldn't be of help to you.

OK, whatever,  thank you, bro.
